### ISSUE TITLE
Does exportConfigurationManifestToFile include JMS resources?

### ISSUE THREAD

**Issue by matt-deboer** [WDR/WDR#106]
I'm using 'exportConfigurationManifestToFile' like so:

    wdr.tools.exportConfigurationManifestToFile(listConfigObjects('Cell'), 'configuration.wdrm')

But I'm noticing the output file contains no reference to any of the JMS resources (connection factories, queues, etc.) that I've created.
Is this just because it may not be implemented yet, or did I miss something? (a quick search over the code-base shows no references to "JMS" in manifest.py or tools.py)

**Comment by mplonka** [comment]
The `exportConfigurationManifestToFile` function accepts another parameter: a hierarchical dictionary describing types of objects being exported, the relevant attributes, keys and child objects. In your example you've omitted this argument, so a default value has been used. Check `wdr.tools._defaultExportConfig` for more details.

Please bear in mind that this specific functionality is still very experimental and is subject to change in the near future based on your and other users' feedback. Hence, it hasn't even been documented yet.

PS: thanks for using WDR!

**Comment by mplonka** [comment]
There was a major refactoring of configuration export in version 0.7. JMS resources are now being exported and imported quite well.
Documenting is still in progress.
Please try and let me know how it works for you.
