### ISSUE TITLE
No wrapper function for AdminControl.completeObjectName

### ISSUE THREAD

**Issue by philowest** [WDR/WDR#114]
I see there's no wrapper function for AdminControl.completeObjectName (http://www-01.ibm.com/support/knowledgecenter/SSEQTP_7.0.0/com.ibm.websphere.nd.doc/info/ae/ae/rxml_admincontrol.html). 

I use this to determine the status of an application (running or not). Not sure if there's a better way to do this? 

If you think a function like this could add value in WDR I'd be happy to create a pull request.

**Comment by mplonka** [comment]
I never thought of wrapping AdminControl.completeObjectName, and I'm not really sure if I understand the difference between `AdminControl.completeObjectName` and other methods that query MBean server.
Maybe an example is going to better illustrate the difference?

In the current WDR you can obtain application status using `getMBean` or `queryMBeans`:

    app = getMBean(type='Application', process='dmgr', name='isclite')
    if app:
        print app.name, app.implementationVersion, app.edition
    else:
        print 'the application does not seem to be running'

An example with `completeObjectName`?

**Comment by philowest** [comment]
Ah, I see my problem now. I tried to make use of getMBean1, which of course raises an exception if no MBean is found. I assumed getMBean would have similar behaviour. 

The example scripts provided with WAS tend to make use of completeObjectName to determine application state, and this is the main reason I was looking to use this function. From what I can see it looks like the main difference is that completeObjectName returns only the first match if there are multiple matches, whereas queryNames returns a list?  

getMBean is what I'm after though. Thanks!

**Comment by mplonka** [comment]
Maybe `AdminControl.completeObjectName` is faster than `AdminControl.queryMBeans`, since it returns only the first match? I'll do some tests against one large cell and compare the results.

**Comment by mplonka** [comment]
Pull request merged. Thanks for contributing!
