### ISSUE TITLE
Especify templates on manifest file

### ISSUE THREAD

**Issue by vtcosta** [WDR/WDR#139]
Is it possible to especify templates within a manifest file, so that those templates are to be used when creating config objects?

By defining a given template somehow in the manifest file, instead of using AdminConfig.create, get the template with AdminConfig.listTemplates, and create the config object with AdminConfig.createUsingTemplate.

That's especially useful for creating DataSources with pre-defined templates.

Nice project by the way.

**Comment by mplonka** [comment]
Templates are not supported yet, but it's probably a good idea to add such functionality.
Watch the 'templates' branch.

Thanks for positive feedback and thanks for using WDR!

**Comment by mplonka** [comment]
Templates can be referenced from configuration manifests in two ways (actual examples for the test suite):

1. using template name if the name is unique

```
Cell
	*name $[ cellName ]
	Node
		*name $[ nodeName ]
		JDBCProvider <DB2 Using IBM JCC Driver (XA)>
			*name Template based provider
			-description Created from "DB2 Using IBM JCC Driver (XA)" template
```

2. using full template id if the template name is not unique

```
Cell
	*name $[ cellName ]
	Node
		*name $[ nodeName ]
		Server <default(templates/servertypes/APPLICATION_SERVER/servers/default|server.xml#Server_1)>
			*name DefaultServerFromTemplate
```

**Comment by mplonka** [comment]
merged into master in https://github.com/WDR/WDR/pull/140

**Comment by mplonka** [comment]
closed for changes, still open for feedback
