### ISSUE TITLE
How to use reference-attributes in manifest?

### ISSUE THREAD

**Issue by vtcosta** [WDR/WDR#141]
First of all, thanks a lot for the patch on templates. I'll give you a feedback about it as soon as I create some scenarios.

Now on to the problem. I have a DataSource (name=MyDataSource) already created, and I need to create a CMPConnectorFactory with a reference to that DataSource. I am trying the below code:

```
Cell
	J2CResourceAdapter
		*name WebSphere Relational Resource Adapter
		CMPConnectorFactory
			*name MyDataSource_CF
			-cmpDatasource
				DataSource
					*name MyDataSource
```

But WDR fails with the following message: Objects being assigned to reference-attributes must not contain keys/attributes/children

What is more strange, is that even tought an exception was thrown, the object is saved. Here is my script:

```python
for node in listConfigObjects('Node'):
	print node.name
	for server in node.listConfigObjects('Server'):
		print " " + server.name
		if server.serverType == 'APPLICATION_SERVER':
			manifestVariables = { 'nodeName': node.name, 'serverName': server.name }
			importConfigurationManifest( 'template.wdrc', manifestVariables)
save()
```

Do you know how to solve these two problems?

**Comment by vtcosta** [comment]
Quick update, just took a quick look at the source and made it work. Is it the right way to do it??

```
Cell
	JDBCProvider
		DataSource #MyDataSourceRef
			*name MyDataSource

Cell
	J2CResourceAdapter
		*name WebSphere Relational Resource Adapter
		CMPConnectorFactory
			*name MyDataSource_CF
			-cmpDatasource
				DataSource &MyDataSourceRef
```

Still, I don't understand why the CMPConnectorFactory was created when there was an error in my template.

**Comment by vtcosta** [comment]
My bad. I was querying AdminConfig.list before exiting the session, and therefore CMPConnectorFactory was listed. When I try to exit the session, it warns me that changes were made but not saved. If I exit the session and log back in, AdminConfig.list doesn't show the CMPConnectorFactory anymore.

So, just to be sure, is the code posted above the right way to use references??

**Comment by mplonka** [comment]
The simple rule about references is that they need to be declared before they're being referenced.

Configuration manifest you cited above is doing exactly that. The only tiny improvement I can think of would be keeping `JDBCProvider` and `J2CResourceAdapter` in the same tree, like this:

```
Cell
	JDBCProvider
		DataSource #MyDataSourceRef
			*name MyDataSource
	J2CResourceAdapter
		*name WebSphere Relational Resource Adapter
		CMPConnectorFactory
			*name MyDataSource_CF
			-cmpDatasource
				DataSource &MyDataSourceRef
```
I'll need to find some time to document references properly. BTW: Pull requests to gh-pages branch are welcome...
