### ISSUE TITLE
chains attribute

### ISSUE THREAD

**Issue by albqmasqeet** [WDR/WDR#145]
In export_sets, for 'TransportChannelService' the chains attribute shouln't be a 'ref', it should be a regular attribute. what was the wisdom behind making that arrtibute a 'ref' ?

**Comment by mplonka** [comment]
Hi Albqmasqeet. It was probably something opposite to wisdom ;)
Thanks for spotting this. Are you OK with submitting a pull request?
Should you find more bugs like this one, please don't hesitate to open a PR. Those for export_sets I can streamline.

Thanks for using WDR!

**Comment by albqmasqeet** [comment]
Thanks for the quick response. I will submit a PR
