### ISSUE TITLE
exportApplicationManifestToFile Attribute Error on execution

### ISSUE THREAD

**Issue by andrevoges** [WDR/WDR#157]
On WDR 8.2 & 8.1 the following error occurs when execution exportApplicationManifestToFile:

WASX7209I: Connected to process "server1" on node WIN-ANDREVNode01 using SOAP connector;  The type of process is: UnManagedProcess
2018-01-16 10:56:13,183 [INFO] using WDR (https://wdr.github.io/WDR/) version 0.8.2
2018-01-16 10:56:13,194 [INFO] the client is connected to host localhost:8880 using SOAP connector
2018-01-16 10:56:13,198 [INFO] the target process is WIN-ANDREVNode01Cell/WIN-ANDREVNode01/server1
WASX7031I: For help, enter: "print Help.help()"
wsadmin>wdr.tools.exportApplicationManifestToFile('mmistia-server-properties-ear', 'mmistia-server-properties-ear.wdra')
WASX7015E: Exception running command: "wdr.tools.exportApplicationManifestToFile('mmistia-server-properties-ear', 'mmistia-server-properties-ear.wdra')"; exception information:
com.ibm.bsf.BSFException: exception from Jython:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
**AttributeError: 'module' object has no attribute 'tools'**

**Comment by mplonka** [comment]
Can't reproduce the issue in any of environments I have access to. Can you please provide some more details on your setup and do a couple of checks:
- what installation of WDR are you using? (client/server side)
- version of Jython
- can you make sure your copy of WDR does not have any local changes?

**Comment by andrevoges** [comment]
Here is all the information I can give to you.

- Websphere version: 9.0
- WDR server side
- We are using WDR as is from GitHub
- Jython version 2.7.0

What we did to correct the issue (had it on 3 different instances) was to change WDR/profile.py and add line after line 26:
- from wdr.tools import *

**Comment by mplonka** [comment]
Introduced missing import, which should solve the problem.

Thanks for using WDR ;)

**Comment by andrevoges** [comment]
Thanks for the support
